### ISSUE TITLE
It's not public on S3

### ISSUE THREAD

**Issue by mateusgalasso** [joshembling/image-optimizer#13]
### What happened?

 FileUpload::make('image')
                    ->label(__('fields.Image'))
                    ->acceptedFileTypes(['image/jpeg', 'image/png'])
                    ->visibility('public')
                    ->optimize('webp')
                    ->downloadable()
                    ->previewable()
                    ->openable(),

It's not going to S3 with the public. should do something like this:
Storage::put($this->record->image, Storage::get($this->record->image), 'public');

### How to reproduce the bug

.

### Package Version

1.3

### PHP Version

8.2

### Laravel Version

10.43

### Which operating systems does with happen with?

macOS

**Comment by joshembling** [comment]
This will be to do with your S3 bucket creds. You will need to configure this in AWS.

**Comment by zxc88645** [comment]
### 錯誤說明

我認為這是一個錯誤，主要出現在 `BaseFileUpload` 的實作中。

---

### 原版 BaseFileUpload 實作

在原版的 `BaseFileUpload` 中，檔案上傳具備選擇公開或私有的功能。程式碼位置：
[GitHub - filamentphp/filament v3.2.117](https://github.com/filamentphp/filament/blob/v3.2.117/packages/forms/src/Components/BaseFileUpload.php#L203)

```php
$storeMethod = $component->getVisibility() === 'public' ? 'storePubliclyAs' : 'storeAs';

return $file->{$storeMethod}(
    $component->getDirectory(),
    $component->getUploadedFileNameForStorage($file),
    $component->getDiskName()
);
```

在此段程式碼中，根據 `getVisibility()` 的結果，選擇使用 `storePubliclyAs` 或 `storeAs` 來儲存圖片，分別代表公開或私有的儲存選項。

---

### image-optimizer 套件中的問題

在 `image-optimizer` 中的 `BaseFileUpload` 實作未明確指定上傳的公開或私有性質。程式碼位置：
[GitHub - joshembling/image-optimizer](https://github.com/joshembling/image-optimizer/blob/main/src/Components/BaseFileUpload.php#L239)

```php
if ($compressedImage) {
    Storage::disk($component->getDiskName())->put(
        $component->getDirectory() . '/' . $filename,
        $compressedImage->getEncoded()
    );

    return $component->getDirectory() . '/' . $filename;
}
```

在這段程式碼中，使用 `Storage::disk($component->getDiskName())->put()` 方法儲存壓縮後的圖片，但未指定儲存的公開或私有性質，這可能會導致圖片無法符合原始程式碼的設計需求，無法選擇是否公開或私有。

---

### 結論

建議在 `image-optimizer` 套件中修改 `Storage::disk(...)->put()` 的實作，以便支持選擇公開或私有的儲存方式，以符合原版 `BaseFileUpload` 的行為。

**Comment by denizaygundev** [comment]
I also had this issue @mateusgalasso @zxc88645 and solved by setting the default driver on the s3 filesystem `'visibility' => 'public'`
