### ISSUE TITLE
[Bug]: Trait HasUploadingMessage not found

### ISSUE THREAD

**Issue by avarik-anam** [joshembling/image-optimizer#15]
### What happened?

error show Trait "Filament\Forms\Components\Concerns\HasUploadingMessage" not found

### How to reproduce the bug

i am create new laravel and filament project and implement image optimizer, and this is the error if i access the page that using FileUpload Component

### Package Version

1.3.1

### PHP Version

8.2.0

### Laravel Version

10

### Which operating systems does with happen with?

Windows

**Comment by joshembling** [comment]
Please read the docs and check out the same issue here https://github.com/joshembling/image-optimizer/issues/12

**Comment by avarik-anam** [comment]
Thank's, it works
