### ISSUE TITLE
[Bug]: Not able to update to v1.3 due to intervention/image ^2.7 dependency

### ISSUE THREAD

**Issue by kaspernowak** [joshembling/image-optimizer#16]
### What happened?

I am on Filament ^3.2.
I am using intervention/laravel-image in other parts of my laravel backend, which causes issues when I want to use `"joshembling/image-optimizer": "^1.3",` and I run `composer update`:
```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires intervention/image-laravel ^1.0 -> satisfiable by intervention/image-laravel[1.0.0, 1.0.1].
    - intervention/image-laravel[1.0.0, ..., 1.0.1] require intervention/image ^3 -> satisfiable by intervention/image[3.0.0, ..., 3.3.3].
    - You can only install one version of a package, so only one of these can be installed: intervention/image[2.7.0, 2.7.1, 2.7.2, 3.0.0, ..., 3.3.3].
    - joshembling/image-optimizer[v1.3.0, ..., v1.3.1] require intervention/image ^2.7 -> satisfiable by intervention/image[2.7.0, 2.7.1, 2.7.2].
    - Root composer.json requires joshembling/image-optimizer ^1.3 -> satisfiable by joshembling/image-optimizer[v1.3.0, v1.3.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

I would expect that these composer update problems would not occur,  which would be fixed if the used version of intervention/image was bumped to ^3?

### How to reproduce the bug

Install intervention/image-laravel with:
```
composer require intervention/image-laravel
```

Then install image-optimzer with:
```
composer require joshembling/image-optimizer
```
Then update `composer.json` to bump `joshembling/image-optimizer` to `^1.3`, then run:
```
composer update
```

OR 

Alternatively just try to install joshembling/image-optimizer v1.3 directly after installing `intervention/image-laravel`:
```
composer require joshembling/image-optimizer:v1.3
```

### Package Version

1.1

### PHP Version

8.2

### Laravel Version

10.43.0

### Which operating systems does with happen with?

macOS

**Comment by joshembling** [comment]
Hi @kaspernowak 

Version `^3.0` of `intervention/image` is not supported in `^10.0.0` of `spatie/laravel-medialibrary`, it relies on `^2.7`. This package supports media library uploads via Filament so until a stable version of Laravel 11 is released, this won't be updated. 

Sorry for the inconvenience.

**Comment by kaspernowak** [comment]
> Hi @kaspernowak 
> 
> Version `^3.0` of `intervention/image` is not supported in `^10.0.0` of `spatie/laravel-medialibrary`, it relies on `^2.7`. This package supports media library uploads via Filament so until a stable version of Laravel 11 is released, this won't be updated. 
> 
> Sorry for the inconvenience. 

Ahh that makes sense, and no worries, I will just run my methods on the create and edit pages decoupled from filament. 

Thank you for taking the time to reply!
