### ISSUE TITLE
[Bug]: failed when composer require joshembling/image-optimizer Laravel 11

### ISSUE THREAD

**Issue by upiw256** [joshembling/image-optimizer#19]
### What happened?

i cannot use composer require joshembling/image-optimizer with error 
```joshembling/image-optimizer[v1.0.0, ..., v1.3.1] require illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.2] but these were not loaded, likely because it conflicts with another require.```
and
```Root composer.json requires joshembling/image-optimizer * -> satisfiable by joshembling/image-optimizer[v1.0.0, ..., v1.3.1].```

### How to reproduce the bug

i cannot use composer require joshembling/image-optimizer with error 
```joshembling/image-optimizer[v1.0.0, ..., v1.3.1] require illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.2] but these were not loaded, likely because it conflicts with another require.```
and
```Root composer.json requires joshembling/image-optimizer * -> satisfiable by joshembling/image-optimizer[v1.0.0, ..., v1.3.1].```

### Package Version

1.3.1

### PHP Version

8.3

### Laravel Version

11

### Which operating systems does with happen with?

Windows

**Comment by joshembling** [comment]
This package isn't available to use with Laravel 11 yet.

Coming soon!
