### ISSUE TITLE
Trait not found 

### ISSUE THREAD

**Issue by alboxe** [joshembling/image-optimizer#21]
### What happened?

When I use the optimize option I get the error Trait "Filament\Forms\Components\Concerns\HasUploadingMessage" not found.
The trait is not in \vendor\filament\forms\src\Concerns. When I put on comment 'use Concerns\HasUploadingMessage;' it's working fine. Version error?

### How to reproduce the bug

Make a Filament form with Forms\Components\SpatieMediaLibraryFileUpload::make('images')
                    ->image()->imageEditor()->optimize('webp')

### Package Version

joshembling/image-optimizer 1.4.0 + Filament 3.1.47

### PHP Version

8.2.15

### Laravel Version

10.48

### Which operating systems does with happen with?

Windows

**Comment by joshembling** [comment]
Same issue described here 

https://github.com/joshembling/image-optimizer/issues/15
