### ISSUE TITLE
Problem with S3 and livewire-tmp folder

### ISSUE THREAD

**Issue by Orclaus** [joshembling/image-optimizer#22]
### What happened?

Getting this error when i add ->optimize('webp') to my FileUploads. and submit a form.
"Unable to find file (livewire-tmp/jeVtd41JPHzi9vyTyczpRHsiPit38g-metadW50aXRsZWQgKDI5IG9mIDMwKS5qcGc=-.jpg)."

From Livewire documentation:
"Livewire stores temporary files in a non-public directory as previously mentioned, therefore, there's no simple way to expose a temporary, public URL to your users for image previewing. If you've configured Livewire to use S3 for temporary file storage, calling ->temporaryUrl() will generate a temporary, signed URL from S3 directly so that you don't hit your Laravel app server for this preview at all."

My bucket is accessible from the internet and works normally. 
However, when I inspect the file permissions inside the livewire-tmp folder, those are not readable from internet. The bucket however is correctly configured, inside my non-temporary folders all uploads are public.  Im not sure if its a Livewire issue (or feature), im pretty sure the bucket and permissions are correct. If the tmp files cannot be read, could this be the reason why its throwing the error? 

Thanks!

### How to reproduce the bug

.env file:
FILESYSTEM_DISK=s3
FILAMENT_FILESYSTEM_DISK=s3

plus your AWS credentials.

In resource form schema, simply:
Forms\Components\FileUpload::make('main_image')
    ->label(__('Main Image'))
    ->image()
    ->directory('images')
    ->required()
    ->maxSize(2048)
    ->optimize('webp') // < throws exception
    ->visibility('public')
    ->downloadable()
    ->previewable()
    ->openable()

When submitting this exception appears:
Unable to find file (livewire-tmp/jeVtd41JPHzi9vyTyczpRHsiPit38g-metadW50aXRsZWQgKDI5IG9mIDMwKS5qcGc=-.jpg).

(The file is present in livewire-tmp/ inside the bucket but cannot be read)

### Package Version

latest

### PHP Version

8.3.1

### Laravel Version

10.48.4

### Which operating systems does with happen with?

Windows

**Comment by joshembling** [comment]
@Orclaus  Thanks for flagging this. 

It seems to be an issue with any FileUpload component, not just this one. I have noticed it in the last few days on a few of my other projects not using this package. 

I should also mention that I never had this issue before until this week. I wonder if something has changed on the Filament/Livewire side?

**Comment by yukebrillianth** [comment]
any updates?

**Comment by majestica** [comment]
any idea how to fix it?

**Comment by Umar-Farooq-Shafi** [comment]
+1

**Comment by nikspyratos** [comment]
To fix this, the temp upload would have to not be on the s3 disk but the server itself.

The closest alternative might be to try and mount the S3 bucket as a filesystem on the server, but a) that's probably got some gotchas anyway and b) it's easier to just not use S3 as the temp disk, I think.

**Comment by ayatamine** [comment]
any update on this error , i lost a whole day searching about it?

**Comment by martinArg96** [comment]
same problem with r2
