### ISSUE TITLE
[Bug]: Unsupported image type image/svg+xml

### ISSUE THREAD

**Issue by Ax3lFernus** [joshembling/image-optimizer#26]
### What happened?

When i try to upload an svg, the GD driver throws this exeption:
`Intervention\Image\Exception\NotReadableException: Unsupported image type image/svg+xml.`
Is there any way to skip optimization just for this file format?
Thanks!

### How to reproduce the bug

When i upload an *.svg file, the `Intervention\Image\Exception\NotReadableException` exeption occurs.

### Package Version

1.4.0

### PHP Version

8.3.0

### Laravel Version

11.0

### Which operating systems does with happen with?

Linux

**Comment by joshembling** [comment]
https://github.com/joshembling/image-optimizer/discussions/11
