### ISSUE TITLE
[Bug]: Cannot use in filamentphp with livewire

### ISSUE THREAD

**Issue by uluumbch** [joshembling/image-optimizer#30]
### What happened?

Is this extension cannot be use inside livewire with filament/forms? would be very happy if this extension could be used on livewire

### How to reproduce the bug

I cannot use the optimize() method after install package. I already do composer update but still doesn't work on livewire with filament/form

### Package Version

latest

### PHP Version

8.2

### Laravel Version

11.8

### Which operating systems does with happen with?

Windows

**Comment by joshembling** [comment]
[No repository provided]
