### ISSUE TITLE
[Bug]: Method 'optimize' not found in \Filament\Forms\Components\FileUpload 

### ISSUE THREAD

**Issue by faizananwerali** [joshembling/image-optimizer#6]
### What happened?

Method 'optimize' not found in \Filament\Forms\Components\FileUpload 

### How to reproduce the bug

follow the readme.md file

### Package Version

latest

### PHP Version

v8.1.19

### Laravel Version

v10.14.0

### Which operating systems does with happen with?

macOS

**Comment by joshembling** [comment]
Hi @faizananwerali 

Thanks for flagging this. Fixed in `v1.2.0`.

https://github.com/joshembling/image-optimizer/releases/tag/v1.2.0
https://packagist.org/packages/joshembling/image-optimizer#v1.2.0

**Comment by faizananwerali** [comment]
Still same error after update

**Comment by joshembling** [comment]
> Still same error after update

I can't recreate this error after updating. Can you send me your repository?

**Comment by faizananwerali** [comment]
Can you please share the demo application repo?

**Comment by joshembling** [comment]
@faizananwerali Yes sure thing - https://github.com/joshembling/image-optimizer-demo

**Comment by Grazulex** [comment]
hello,still no feedback..I have the same error but only in prod, not local :-(
