### ISSUE TITLE
[Bug]: Class "Intervention\Image\ImageManagerStatic" not found

### ISSUE THREAD

**Issue by urufudev** [joshembling/image-optimizer#7]
### What happened?

I followed the installation steps correctly, but when using it it shows the class not found error.
Step to install:
`composer require joshembling/image-optimizer`

### How to reproduce the bug

After installing, I tried to perform the optimization, but it shows me the following error:
`Class "Intervention\Image\ImageManagerStatic" not found`.

### Package Version

lastest

### PHP Version

8.1.12

### Laravel Version

10.28.0

### Which operating systems does with happen with?

Windows

**Comment by EsiNakesy** [comment]
I have the same issue, Any news?

**Comment by joshembling** [comment]
Hi @urufudev, @EsiNakesy 

Thanks for flagging this. Fixed in `v1.2.0`.

https://github.com/joshembling/image-optimizer/releases/tag/v1.2.0
https://packagist.org/packages/joshembling/image-optimizer#v1.2.0
