### ISSUE TITLE
[Bug]: Undefined variable $getUploadingMessage 

### ISSUE THREAD

**Issue by williamengbjerg** [joshembling/image-optimizer#9]
### What happened?

After updating filament, I encountered errors indicating an `Undefined variable $getUploadingMessage`. Any insights or resolutions to rectify this issue would be greatly appreciated. Thanks. 

### How to reproduce the bug

Once updating to latest filament version

### Package Version

1.2.0

### PHP Version

8.2.15

### Laravel Version

10.42.0

**Comment by akromjon** [comment]
I am also getting the same issue:

                  Section::make([
                        FileUpload::make('image')
                            ->label(__('Image'))
                            ->image()
                            ->optimize('jpg')
                            ->resize(50),

                        TextInput::make('read_duration')
                            ->label(__('Read Duration (in minutes)'))
                            ->disabled(),

                        Select::make('categories')
                            ->multiple()
                            ->relationship(titleAttribute: 'title')
                            ->preload()
                    ]),

**Comment by joshembling** [comment]
Hi @williamengbjerg @akromjon 

Thank you for raising these issues. These have now been fixed in the latest version, please upgrade to v1.3.0. 

https://github.com/joshembling/image-optimizer/compare/v1.2.0...v1.3.0
